export const ONE_HOUR = 60 * 60 * 1000
export const THIRTY_MINUTES = ONE_HOUR / 2
export const TWO_HOURS = 2 * ONE_HOUR
export const THREE_HOURS = 3 * ONE_HOUR
export const FOUR_HOURS = 4 * ONE_HOUR
export const FIVE_HOURS = 5 * ONE_HOUR
export const SIX_HOURS = 6 * ONE_HOUR
export const SEVEN_HOURS = 7 * ONE_HOUR
export const EIGHT_HOURS = 8 * ONE_HOUR
export const NINE_HOURS = 9 * ONE_HOUR
export const TEN_HOURS = 10 * ONE_HOUR
export const ELEVEN_HOURS = 11 * ONE_HOUR
export const TWELVE_HOURS = 12 * ONE_HOUR
export const THIRTEEN_HOURS = 13 * ONE_HOUR
export const FOURTEEN_HOURS = 14 * ONE_HOUR
export const FIFTEEN_HOURS = 15 * ONE_HOUR
export const SIXTEEN_HOURS = 16 * ONE_HOUR
